feat(all): 多数据源场景，默认拆分api-lock.json到每个数据源目录下
alibaba/pont pull request #263
Opened 2021-12-31 02:31 UTC by z979054461

## What kind of change does this PR introduce(这个 PR 引入了什么样的变化)?

- [ ] Bugfix(修正错误)
- [ ] Feature(新功能)
- [x] Refactor(重构)
- [ ] Build-related changes(与构建相关的更改)
- [ ] Other, please describe(其他，请描述):

## Does this PR introduce a breaking change(这次 PR 引入了一个重大变化吗)?

- [x] Yes(是)
- [ ] No(否)

If yes, please describe the impact and migration path for existing applications(如果是，请描述现有应用程序的影响和迁移路径):
多数据源的场景，打开vscode检测api-lock.json之后会将其备份为api-lock.json.bak，然后在数据源子目录下重新生成独立的api-lock.json

## The PR fulfills these requirements(PR 符合以下要求)

- [ ] All tests are passing(所有测试都通过)

## Other information(其他信息)

有一个破坏性变更，用户如果覆盖了`pontTemplate.ts`文件中的以下函数，需要适应性调整：
**getOriginFileStructures**、**getMultipleOriginsFileStructures**、**getLockContent**

2021-12-31 02:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/alibaba/pont?pullRequest=263) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/alibaba/pont?pullRequest=263) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/alibaba/pont?pullRequest=263) it.</sub>

2022-01-04 02:27 UTC, wilsoncook requested changes

2022-01-04 02:27 UTC, wilsoncook commented on packages/pont-engine/src/manage.ts
> +  async readLockFile(): Promise<Array<StandardDataSource>> {
readLockFile既返回Promise，又返回原始非Promise，类型要明确下

2022-01-04 13:52 UTC, z979054461 commented on packages/pont-engine/src/manage.ts
> +  async readLockFile(): Promise<Array<StandardDataSource>> {
这里返回值就是Promise，会resolve一个StandardDataSource类型的数组

2022-01-13 03:02 UTC, merged